FROM debian:trixie-slim
RUN apt update
RUN apt install -y ca-certificates
# Add a cert-update script
COPY update-certs.sh /update-certs.sh
RUN chmod +x /update-certs.sh
ENTRYPOINT ["/update-certs.sh"]
